sudo: required
services:
  - docker

before_install:
  - docker build -t roshand1/multiconainer-test -f ./ReactBolerPlateWithWebpackExpress/Dockerfile.dev ./ReactBolerPlateWithWebpackExpress

script:
  - echo 'test ran'

after_success:
  - docker build -t roshand1/multi-reactapp ./ReactBolerPlateWithWebpackExpress
  - docker build -t roshand1/multi-nginx ./nginx
  - docker build -t roshand1/multi-node-auth-service ./node-auth-service
  - docker images

# Login to docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take this image and push in docker hub using docker cli
  - docker push roshand1/multi-reactapp
  - docker push roshand1/multi-nginx
  - docker push roshand1/multi-node-auth-service

  # build
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-145586335677"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"