sudo: required
services:
  - docker

before_install:
  - docker build -t rdangal1/reactboilerplate -f Dockerfile.dev .

script:
  - echo 'test ran'

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app-docker"
  env: "Reactappdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-145586335677"
  bucket_path: "react-app-docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"